<div class="input-group">
    <?php
    if(isset($provinces))
    {


        foreach($provinces as $province){



    ?>
    <h4>Province From</h4>

    <!-- Single button -->
    <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            Action <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
        </ul>
    </div>

    <h4> Province To</h4>
    <?php
        }

    }else{
        echo "Error!";
    }
    ?>
</div>