<?php
$messages = $this->flashSession->getMessages();

if(isset($messages['error']) && count($messages['error']) != 0){
    foreach($messages['error'] as $message){ ?>
    <div class="container">
        <div class="alert alert-danger alert-dismissable" data-dismiss="alert" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <?=$message?>
        </div>
    </div>

<?php
    }
}
if(isset($messages['success']) && count($messages['success']) != 0){
    foreach($messages['success'] as $message){?>
        <div class="container">
            <div class="alert alert-success alert-dismissable" data-dismiss="alert" role="alert">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <?=$message?>
            </div>
        </div>
    <?php
    }
}
if(isset($messages['notice']) && count($messages['notice']) != 0){
    foreach($messages['notice'] as $message){?>
        <div class="container">
            <div class="alert alert-notice alert-dismissable" data-dismiss="alert" role="alert">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <?=$message?>
            </div>
        </div>
    <?php
    }
}
if(isset($messages['warning']) && count($messages['warning']) != 0){
    foreach($messages['warning'] as $message){?>
        <div class="container">
            <div class="alert alert-warning alert-dismissable" data-dismiss="alert" role="alert">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <?=$message?>
            </div>
        </div>
    <?php
    }
}