<div class="container">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel-default">
            <div class="panel-body">
                <form role="form" action="/campaign/create" method="POST">
                    <div class="form-group">
                        <label for="campaign_description">Campaign description</label>
                        <input name="campaign_description" type="text" class="form-control" id="campaign_Description" placeholder="Campaign description">
                    </div>
                    <button type="submit" class="btn btn-default">Create my campaign!</button>
                </form>
            </div>
        </div>
    </div>
</div>