<div class="container">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel-default">
            <div class="panel-body">
                <form role="form" action="/user/register" method="POST">
                    <div class="form-group">
                        <label for="username">Username</label>
                        <input name="username" type="text" class="form-control" id="username" placeholder="Enter username">
                    </div>
                    <div class="form-group">
                        <label for="email">Email address</label>
                        <input name="email" type="email" class="form-control" id="email" placeholder="Enter email">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input name="password" type="password" class="form-control" id="password" placeholder="Password">
                        <input name="confirmpassword" type="password" class="form-control" id="confirmpassword" placeholder="Confirm your password">
                    </div>

                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="rememberme"> Remember me
                        </label>
                    </div>
                    <button type="submit" class="btn btn-default">Register me!</button>
                </form>
            </div>
        </div>
    </div>
</div>