<!DOCTYPE html>

<html>

<head>
    <meta charset="utf-8" >
    <?php
        echo Phalcon\Tag::getTitle();
        echo Phalcon\Tag::stylesheetLink('css/bootstrap.min.css');
    ?>
</head>

<body>

    <?php
        $this->partial('shared/navbar');
        $this->partial('shared/flashMessages');

        echo $this->getContent();

        echo Phalcon\Tag::javascriptInclude('//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js');
        echo Phalcon\Tag::javascriptInclude('js/bootstrap.min.js');
        $this->assets->outputJs();
    ?>
</body>

</html>

