<h1>Order create dashboard</h1>

<?php
if(isset($provinces_from)){
    foreach($provinces_from as $province){
        echo $province->id_province." - ";
        echo $province->points." - ";
        foreach($province->connection as $connection){
            echo ":".$connection->to_province;
        }

        //echo Phalcon\Tag::linkTo("campaign/join/".$campaign->id,"JOIN");
        echo "<br>";

    }
}else{
    echo "Not set";
}
?>